export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sku TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    image TEXT NOT NULL DEFAULT '',
    wholesale_price REAL NOT NULL,
    retail_price REAL NOT NULL,
    category TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT '待核查',
    checked INTEGER NOT NULL DEFAULT 0,
    backend_url TEXT NOT NULL DEFAULT '',
    frontend_url TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS schedules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    work_date TEXT NOT NULL,
    work_time TEXT NOT NULL,
    title TEXT NOT NULL,
    tag TEXT NOT NULL,
    color TEXT NOT NULL DEFAULT '#466b5c',
    completed INTEGER NOT NULL DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS daily_logs (
    work_date TEXT PRIMARY KEY,
    completed_text TEXT NOT NULL DEFAULT '',
    followup_text TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_schedules_work_date ON schedules(work_date)`,
  `CREATE INDEX IF NOT EXISTS idx_products_status ON products(status)`,
  `CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_date TEXT NOT NULL,
    order_no TEXT NOT NULL UNIQUE,
    sku TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    revenue REAL NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT '已付款',
    source_order_no TEXT NOT NULL DEFAULT '',
    platform_sku TEXT NOT NULL DEFAULT '',
    customer_info TEXT NOT NULL DEFAULT '',
    item_price REAL NOT NULL DEFAULT 0,
    is_replacement INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_orders_date_sku ON orders(order_date, sku)`,
  `CREATE INDEX IF NOT EXISTS idx_orders_shop_date ON orders(shop, order_date)`,
  `CREATE TABLE IF NOT EXISTS sales_sku_mappings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    platform TEXT NOT NULL,
    sales_sku TEXT NOT NULL,
    system_sku TEXT NOT NULL,
    display_name TEXT NOT NULL DEFAULT '',
    active INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(platform, sales_sku)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_mappings_system_sku ON sales_sku_mappings(system_sku)`,
  `CREATE TABLE IF NOT EXISTS sales_sku_mappings_v2 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    shop TEXT NOT NULL,
    platform TEXT NOT NULL,
    sales_sku TEXT NOT NULL,
    system_sku TEXT NOT NULL,
    display_name TEXT NOT NULL DEFAULT '',
    active INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(shop, platform, sales_sku)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_mappings_v2_shop_system ON sales_sku_mappings_v2(shop, system_sku)`,
  `CREATE TABLE IF NOT EXISTS product_checks (
    shop TEXT NOT NULL,
    sales_sku TEXT NOT NULL,
    checked INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(shop, sales_sku)
  )`,
  `CREATE TABLE IF NOT EXISTS link_metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    shop TEXT NOT NULL,
    metric_date TEXT NOT NULL,
    platform_sku TEXT NOT NULL,
    link_url TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    rank_position INTEGER NOT NULL DEFAULT 0,
    rating REAL NOT NULL DEFAULT 0,
    review_count INTEGER NOT NULL DEFAULT 0,
    low_star_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(shop, metric_date, platform_sku)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_link_metrics_shop_date ON link_metrics(shop, metric_date DESC)`,
  `CREATE TABLE IF NOT EXISTS monitor_targets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    shop TEXT NOT NULL,
    platform_sku TEXT NOT NULL,
    sales_sku TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    link_url TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'Furniture',
    keyword TEXT NOT NULL DEFAULT '',
    priority INTEGER NOT NULL DEFAULT 1,
    active INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(shop, platform_sku)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_monitor_targets_shop_active ON monitor_targets(shop, active, priority DESC)`,
];
